# Generated by Django 5.2.7 on 2025-10-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('traffic_accident', 'Accidente de tráfico'), ('road_closure', 'Cierre de vía'), ('traffic_jam', 'Congestión vehicular'), ('road_hazard', 'Peligro en la vía'), ('weather', 'Condición climática'), ('flooding', 'Inundación'), ('construction', 'Obra en construcción'), ('police', 'Presencia policial'), ('emergency', 'Emergencia'), ('public_event', 'Evento público'), ('broken_vehicle', 'Vehículo varado'), ('other', 'Otro')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AlertCategory',
        ),
    ]
