# Generated by Django 5.2.7 on 2025-10-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_alert_category_delete_alertcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('traffic_accident', 'Accidente de tráfico'), ('road_closure', 'Cierre de vía'), ('traffic_jam', 'Congestión vehicular'), ('road_hazard', 'Peligro en la vía'), ('flooding', 'Inundación'), ('construction', 'Obra en construcción'), ('police', 'Presencia policial'), ('emergency', 'Emergencia'), ('public_event', 'Evento público'), ('other', 'Otro')], max_length=50),
        ),
    ]
